image:
  file: Dockerfile

# start up tasks
tasks:
- init: ./mvnw package -DskipTests
  command: java -jar target/*.jar
- init: while ! (mysqladmin ping 2> /dev/null); do sleep 2; echo 'Waiting for mySQL... sit tight!'; done && mysql < /workspace/swefundamentals/src/main/resources/db/mysql/schema.sql && mysql < /workspace/swefundamentals/src/main/resources/db/mysql/data.sql

# exposed ports
ports:
- port: 8080
  onOpen: open-preview
