image:
  file: Dockerfile

# start up tasks
tasks:
- init: ./mvnw package -DskipTests
  command: java -jar target/*.jar
- init: mysql < /workspace/swefundamentals/src/main/resources/db/mysql/schema.sql && mysql < /workspace/swefundamentals/src/main/resources/db/mysql/data.sql

# exposed ports
ports:
- port: 8080
  onOpen: open-preview
